name: CI

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  typecheck:
    uses: ./.github/workflows/typecheck.yml

  test:
    uses: ./.github/workflows/test.yml
