name: Test

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  pytest:
    strategy:
      matrix:
        test-profile:
          - dev
          - dev_slow
          - ci
          - ci_slow
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "**/pyproject.toml"
      - run: python3 -m pip install pip --upgrade
      - run: python3 -m pip install --pre --extra-index-url https://download.pytorch.org/whl/nightly/cpu '.[test]'
      - run: echo "::add-matcher::./.github/problem_matchers/pytest.jsonc"
      - run: pytest -n1 --durations=0 --hypothesis-show-statistics --hypothesis-profile ${{ matrix.test-profile }}
      - run: echo "::remove-matcher owner=pytest::"
