name: Test

defaults:
  run:
    shell: bash

on:
  workflow_call:

jobs:
  pytest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "**/pyproject.toml"
      - run: python3 -m pip install pip --upgrade
      - run: python3 -m pip install --pre --extra-index-url https://download.pytorch.org/whl/nightly/cpu '.[test]'
      - run: echo "::add-matcher::./.github/problem_matchers/pytest.jsonc"
      - run: pytest -n1 --durations=0 --hypothesis-show-statistics --hypothesis-profile ci_cpu
      - run: echo "::remove-matcher owner=pytest::"
