name: Typecheck

defaults:
  run:
    shell: bash

on:
  workflow_call:

jobs:
  mypy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "**/pyproject.toml"
      - run: python3 -m pip install pip --upgrade
      - run: python3 -m pip install --pre --extra-index-url https://download.pytorch.org/whl/nightly/cpu '.[typecheck,test]'
      - run: mypy ./mfsr_utils ./tests

  pyright:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "**/pyproject.toml"
      - run: python3 -m pip install pip --upgrade
      - run: python3 -m pip install --pre --extra-index-url https://download.pytorch.org/whl/nightly/cpu '.[typecheck,test]'
      - run: pyright ./mfsr_utils ./tests
      - run: pyright --verifytypes mfsr_utils --ignoreexternal --pythonversion 3.10 --pythonplatform Linux --verbose
